### ISSUE TITLE
'luajit demo_luajit_model.lua' terminated by signal SIGSEGV (Address boundary error)

### ISSUE THREAD

**Issue by whoamigo** [r-lyeh/FWK#20]
Hi @r-lyeh,

I'm getting this crash with the last commit:

```shell
luajit demo_luajit_model.lua
000.000s|Monitor: Color LCD (60Hz, vsync=1)w_create_from_handle|fwk_window.c:153
000.000s|GPU device: AMD Radeon Pro 450 OpenGL Enginerom_handle|fwk_window.c:154
000.000s|GPU driver: 4.1 ATI-4.6.20  |window_create_from_handle|fwk_window.c:155
000.018s|Compiling shader                               |shader|fwk_render.c:833
000.019s|Shader.attribute[0]=att_position               |shader|fwk_render.c:860
Deleting 000% art//demos/audio/larry.txt
'luajit demo_luajit_model.lua' terminated by signal SIGSEGV (Address boundary error)
```
I hope the error message gives you enough clues.

Thanks

**Comment by r-lyeh** [comment]
Can you delete all the zip files and give it another run?

**Comment by whoamigo** [comment]
It didn't make any difference. I even tried with the zip files of the previous commit to no avail.

**Comment by r-lyeh** [comment]
oh wow, there was a nasty bug in the cooking stage when using "../" folders that did not show up easily. i've pushed a fix for that, among other bits. could you give latest commit another try?

**Comment by whoamigo** [comment]
I am still getting the same error, unfortunately.

**Comment by r-lyeh** [comment]
Ok, those 0-byte zips are fine; that's part of the cook process and it is a normal procedure when syncing up content. it is just that the app crashed before populating the new .zip files.

let's do another test. does it work if you...
1. comment the `XMACRO(BIND_ALL);` line in fwk.c:12722
2. rebuild the dlls `sh MAKE.bat dll`
3. copy the libfwk.dylib file into /usr/lib (not quite sure about whether this is actually needed on OSX, at this point).

**Comment by r-lyeh** [comment]
also, try to run luajit like this. hopefully that will give us a detailed callstack about where it is crashing.

`lldb --args luajit demo_luajit_model.lua` then press `r` and `ENTER`.

**Comment by whoamigo** [comment]
OK, so these steps yield the same error:
```shell
1. comment the XMACRO(BIND_ALL); line in fwk.c:127222.
2. rebuild the dlls sh MAKE.bat dll
3. copy the libfwk.dylib file into /usr/lib (not quite sure about whether this is actually needed on OSX, at this point).
```
Now here's the output of running it through the debugger:
```shell
lldb -f luajit demo_luajit_model.lua
(lldb) target create "/usr/local/bin/luajit"
Current executable set to '/usr/local/bin/luajit' (x86_64).
(lldb) settings set -- target.run-args  "demo_luajit_model.lua"
(lldb) r
Process 88487 launched: '/usr/local/bin/luajit' (x86_64)
2022-03-12 17:15:05.013283+0100 luajit[88487:1407748] SecTaskLoadEntitlements failed error=22 cs_flags=20, pid=88487
2022-03-12 17:15:05.013405+0100 luajit[88487:1407748] SecTaskCopyDebugDescription: luajit-2.1.0-bet[88487]/0#-1 LF=0
                                           |window_create_from_handle|fwk_window000.000s|Monitor: Color LCD (60Hz, vsync=1)
                                           |window_create_from_handle|fwk_window000.000s|GPU device: AMD Radeon Pro 450 OpenGL Engine
                                           |window_create_from_handle|fwk_window000.000s|GPU driver: 4.1 ATI-4.6.20
000.016s|Compiling shadershader|fwk_render.c:833
000.018s|Shader.attribute[0]=att_positionr.c:860
2022-03-12 17:15:07.167805+0100 luajit[88487:1407748] [plugin] AddInstanceForFactory: No factory registered for id <CFUUID 0x109f20>
2022-03-12 17:15:07.208441+0100 luajit[88487:1407748]   saved enable noise cancellation setting is the same as the default (=1)
Deleting 000% art//demos/audio/coin.wav
Process 88487 stopped
* thread #9, stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
    frame #0: 0x000000000210f919 libfwk.dylib`zip_append_file(z=0x00000000005101f0, entryname="art//demos/audio/coin.wav", comment="0", in=0x00007fff80773580, compress_level=0) at 3rd_archive.h:553:33
Target 0: (luajit) stopped.
(lldb) bt
* thread #9, stop reason = EXC_BAD_ACCESS (code=1, address=0x8)
  * frame #0: 0x000000000210f919 libfwk.dylib`zip_append_file(z=0x00000000005101f0, entryname="art//demos/audio/coin.wav", comment="0", in=0x00007fff80773580, compress_level=0) at 3rd_archive.h:553:33
    frame #1: 0x00000000021aca16 libfwk.dylib`cook(userdata=0x000000000a633db8) at fwk_cooker.c:448:9
    frame #2: 0x00000000021ac692 libfwk.dylib`cook_async(userptr=0x000000000a633db8) at fwk_cooker.c:511:15
    frame #3: 0x00007fff2047a8fc libsystem_pthread.dylib`_pthread_start + 224
    frame #4: 0x00007fff20476443 libsystem_pthread.dylib`thread_start + 15
(lldb)
```

**Comment by r-lyeh** [comment]
Hard to say from that callstack; it could take us a few retries. I've pushed an update. Let me know how that one behaves.

**Comment by whoamigo** [comment]
Sorry for the bad news @r-lyeh. Now the C demos are also crashing.

```shell
'./demo_model' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by whoamigo** [comment]
./demo_model (demo_model.c) still crashes with last commit. Same error, same line.

**Comment by whoamigo** [comment]
@r-lyeh please remove this line: `sudo cp libfwk.dylib /usr/lib` because it requires to have **System Integrity Protection (SIP)** disabled and mounting `/` as writable, which is possible but not handy as it requires a system reboot after each disabling/re-enabling.

**Comment by r-lyeh** [comment]
I think I've recreated your issue on Linux. Stay tuned.

**Comment by whoamigo** [comment]
Awesome! Everything is working again!

**Comment by r-lyeh** [comment]
glad it worked finally :D
i've noticed there is a coredump when exiting luajit on linux but that's a different issue.
is it coredumping on osx as well? i might need to look into that soon-ish

**Comment by whoamigo** [comment]
Where are you getting this?

**Comment by r-lyeh** [comment]
it coredumps here on linux right after closing the demo_luajit_model.lua window

**Comment by whoamigo** [comment]
I haven't noticed this on macOS.

**Comment by r-lyeh** [comment]
np, i will look into that in any case.
thanks for all the reports as usual!

**Comment by whoamigo** [comment]
You're welcome. It's all fun!
